ci(gha): fix prod deploy script

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -84,12 +84,29 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-     - name: run linting
-       id: lint
-       run: ${{ steps.detect-package-manager.outputs.runner }} run lint
-     - name: run tests
-       id: test
-       run: ${{ steps.detect-package-manager.outputs.runner }} run test
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          # elif [ -f "${{ github.workspace }}/package.json" ]; then
+          #   echo "manager=npm" >> $GITHUB_OUTPUT
+          #   echo "command=ci" >> $GITHUB_OUTPUT
+          #   echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          #   exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: run linting
+        id: lint
+        run: ${{ steps.detect-package-manager.outputs.runner }} lint
+      - name: run tests
+        id: test
+        run: ${{ steps.detect-package-manager.outputs.runner }} test
 
   # Deployment job
   deploy:
